<style>
#mywrapper {
	margin: 40px 0px 40px 0px;
    width: 100%;
}
</style>
<div id="mywrapper">
	<span class="c1">WHAT&nbsp;DO&nbsp;WE&nbsp;DO?<br />
	</span> <br /> <span class="c1">MobileShop&nbsp;gives&nbsp;you&nbsp;a&nbsp;chance&nbsp;to&nbsp;quickly&nbsp;and&nbsp;easily&nbsp;find&nbsp;the&nbsp;phone&nbsp;you&nbsp;want&nbsp;and&nbsp;have&nbsp;it&nbsp;delivered&nbsp;to&nbsp;your&nbsp;home&nbsp;in&nbsp;no&nbsp;time,&nbsp;regardless&nbsp;of&nbsp;your&nbsp;location,&nbsp;as&nbsp;long&nbsp;as&nbsp;it&nbsp;is&nbsp;in&nbsp;one&nbsp;of&nbsp;the&nbsp;countries&nbsp;of&nbsp;the&nbsp;EU.<br />
	</span> <br /> <span class="c1">WHY&nbsp;DO&nbsp;CUSTOMERS&nbsp;LOVE&nbsp;US?<br />
	</span> <br /> <span class="c1">We&nbsp;have&nbsp;been&nbsp;in&nbsp;the&nbsp;business&nbsp;for&nbsp;quite&nbsp;a&nbsp;while&nbsp;now,&nbsp;and&nbsp;it&nbsp;that&nbsp;time&nbsp;we&nbsp;have&nbsp;not&nbsp;only&nbsp;managed&nbsp;to&nbsp;make&nbsp;close&nbsp;relationships&nbsp;with&nbsp;numerous&nbsp;suppliers&nbsp;all&nbsp;over&nbsp;the&nbsp;world,&nbsp;but&nbsp;also&nbsp;to&nbsp;recognize&nbsp;what&nbsp;people&nbsp;need.&nbsp;This&nbsp;means&nbsp;that&nbsp;we&nbsp;are&nbsp;always&nbsp;able&nbsp;to&nbsp;offer&nbsp;all&nbsp;the&nbsp;latest&nbsp;phones,&nbsp;great&nbsp;prices,&nbsp;reliable&nbsp;service,&nbsp;fast&nbsp;delivery&nbsp;and&nbsp;premium&nbsp;customer&nbsp;support.<br />
	</span> <br /> <span class="c1">The&nbsp;Story<br />
	</span> <br /> <span class="c1">BEGINNING<br />
	</span> <br /> <span class="c1">MobileShop&nbsp;website&nbsp;was&nbsp;launched&nbsp;in&nbsp;2011,&nbsp;but&nbsp;its&nbsp;story&nbsp;actually&nbsp;began&nbsp;some&nbsp;8&nbsp;years&nbsp;before&nbsp;that&nbsp;when&nbsp;a&nbsp;group&nbsp;of&nbsp;college&nbsp;friends&nbsp;decided&nbsp;to&nbsp;go&nbsp;into&nbsp;business&nbsp;together.&nbsp;We&nbsp;started&nbsp;selling&nbsp;phones&nbsp;in&nbsp;shops,&nbsp;but&nbsp;our&nbsp;combined&nbsp;ambition,&nbsp;drive&nbsp;and&nbsp;abilities&nbsp;soon&nbsp;made&nbsp;us&nbsp;look&nbsp;for&nbsp;new&nbsp;challenges&nbsp;and&nbsp;new&nbsp;markets.&nbsp;Starting&nbsp;an&nbsp;online&nbsp;shop&nbsp;provided&nbsp;for&nbsp;both&nbsp;and&nbsp;allowed&nbsp;us&nbsp;to&nbsp;develop&nbsp;a&nbsp;strong&nbsp;international&nbsp;presence&nbsp;in&nbsp;a&nbsp;number&nbsp;of&nbsp;EU&nbsp;countries.<br />
	</span> <br /> <span class="c1">TODAY<br />
	</span> <br /> <span class="c1">Collective&nbsp;experience&nbsp;of&nbsp;our&nbsp;team&nbsp;members&nbsp;and&nbsp;the&nbsp;years&nbsp;we&nbsp;have&nbsp;spent&nbsp;in&nbsp;the&nbsp;business&nbsp;allowed&nbsp;us&nbsp;to&nbsp;develop&nbsp;a&nbsp;vast&nbsp;network&nbsp;of&nbsp;suppliers,&nbsp;ensuring&nbsp;that&nbsp;our&nbsp;customers&nbsp;will&nbsp;always&nbsp;find&nbsp;what&nbsp;they&nbsp;are&nbsp;looking&nbsp;for.&nbsp;This&nbsp;also&nbsp;means&nbsp;that&nbsp;we&nbsp;are&nbsp;able&nbsp;to&nbsp;offer&nbsp;great&nbsp;prices,&nbsp;which&nbsp;are&nbsp;constantly&nbsp;being&nbsp;updated&nbsp;and&nbsp;follow&nbsp;the&nbsp;shifts&nbsp;in&nbsp;the&nbsp;market.<br />
	</span> <br /> <span class="c1">Our&nbsp;affordability,&nbsp;fast&nbsp;and&nbsp;reliable&nbsp;delivery,&nbsp;and&nbsp;the&nbsp;fact&nbsp;that&nbsp;you&nbsp;will&nbsp;always&nbsp;be&nbsp;able&nbsp;to&nbsp;find&nbsp;the&nbsp;phone&nbsp;that&nbsp;you&nbsp;are&nbsp;looking&nbsp;for&nbsp;in&nbsp;our&nbsp;offer,&nbsp;have&nbsp;made&nbsp;us&nbsp;stand&nbsp;out&nbsp;in&nbsp;the&nbsp;market,&nbsp;but&nbsp;they&nbsp;are&nbsp;simply&nbsp;symptoms&nbsp;of&nbsp;our&nbsp;dedication&nbsp;to&nbsp;what&nbsp;we&nbsp;are&nbsp;doing&nbsp;and&nbsp;our&nbsp;desire&nbsp;to&nbsp;constantly&nbsp;keep&nbsp;improving.&nbsp;We&nbsp;know&nbsp;that&nbsp;in&nbsp;order&nbsp;to&nbsp;do&nbsp;that,&nbsp;we&nbsp;need&nbsp;to&nbsp;keep&nbsp;in&nbsp;close&nbsp;touch&nbsp;with&nbsp;our&nbsp;customers&nbsp;and&nbsp;listen&nbsp;to&nbsp;their&nbsp;suggestions&nbsp;and&nbsp;critiques.&nbsp;This&nbsp;is&nbsp;why&nbsp;our&nbsp;customer&nbsp;service,&nbsp;which&nbsp;is&nbsp;always&nbsp;there&nbsp;to&nbsp;answer&nbsp;any&nbsp;question&nbsp;that&nbsp;you&nbsp;may&nbsp;have,&nbsp;is&nbsp;just&nbsp;as&nbsp;willing&nbsp;to&nbsp;listen&nbsp;as&nbsp;it&nbsp;is&nbsp;to&nbsp;inform.</span>

</div>